<?php

namespace Cserobiul\BurstTransmitsmsApi;

use Illuminate\Support\ServiceProvider;

class TransmitsmsServiceProvider extends ServiceProvider
{
    public function boot(){
        $this->app->bind('transmitsms_api', function($app) {
            return new TransmitsmsAPI();
        });

        $this->mergeConfigFrom(
            __DIR__.'/config/transmitsms_api.php', 'transmitsms_api'
        );
        $this->publishes([
            __DIR__.'/config/transmitsms_api.php' => config_path('transmitsms_api.php'),
        ]);
    }

    public function register()
    {
        parent::register(); // TODO: Change the autogenerated stub
    }
}
